#!/bin/bash
source $DIR/functions/successful
source $DIR/functions/check_package

[ $(check_package python3-pip) == 0 ] && DEPENDENCIES+=("python3-pip")
[ $(check_package apache2) == 0 ] && DEPENDENCIES+=("apache2")

[ $(check_package xterm) == 0 ] && DEPENDENCIES+=("xterm")
[ $(check_package xinit) == 0 ] && DEPENDENCIES+=("xinit")
[ $(check_package xinput) == 0 ] && DEPENDENCIES+=("xinput")
[ $(check_package xserver-xorg) == 0 ] && DEPENDENCIES+=("xserver-xorg")
[ $(check_package xserver-xorg-video-fbdev) == 0 ] && DEPENDENCIES+=("xserver-xorg-video-fbdev")
[ $(check_package x11-xserver-utils) == 0 ] && DEPENDENCIES+=("x11-xserver-utils")
[ $(check_package matchbox) == 0 ] && DEPENDENCIES+=("matchbox")
[ $(check_package unclutter) == 0 ] && DEPENDENCIES+=("unclutter")
[ $(check_package $BROWSER) == 0 ] && DEPENDENCIES+=("$BROWSER")

echo ""
if [ ${#DEPENDENCIES[@]} -ne 0 ]
then
	echo "Running apt-get update (this will take a while)"
	echo "Do NOT switch off the Pi or close this console until done!"
	runCmd apt-get update
	successful $?

	echo ""
	echo "Installing dependencies (${DEPENDENCIES[@]}):"
	runCmd apt-get install --yes --no-install-recommends ${DEPENDENCIES[@]}

    echo ""
	echo "Removing dependencies:"
    runCmd apt purge wolfram-engine scratch nuscratch sonic-pi idle3 -y
    runCmd apt purge smartsim java-common libreoffice* -y
    runCmd apt clean
    runCmd apt autoremove -y

	successful $?
else
	echo "Skipping installation of dependencies:"
	echo " - All dependencies are already installed"
fi