#!/bin/bash
source $DIR/functions/do_exit
source $DIR/functions/color

# Check if stretch is installed and force GLDriver for Chromium
if [ "$ENABLE_GLDRIVER" == true ]
then
	DEB_VERSION=$(cat /etc/os-release | grep -P 'VERSION_ID="([0-9]+)"')
	if [ "$DEB_VERSION" == 'VERSION_ID="9"' ]
	then
		echo ""
		echo "Detected Stretch build!"
		echo "Enabling GLDriver 'G1 GL (Full KMS)' for Stretch:";
		runCmd raspi-config nonint do_gldriver G1
	fi
fi

# Check if kernel can run chromium-browser
# Legacy code for WaveShare
if [ "$BROWSER" == "chromium-browser" ]
then
	if [ -n "$(chromium-browser 2>&1 | grep 'undefined symbol: mmal_vc_init_fd')" ]
	then
		echo ""
		echo -e "$(color 'red' 'WARNING!')";
		echo -e "$(color 'red' 'chromium-browser is currently unable to run on your device!!')"
		echo ""
		do_exit
	fi
fi