#!/bin/bash
DIR=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

# Default variables
DEBUG=false
BROWSER="chromium-browser"
FORCE=false
XORG_DIR="/usr/share/X11/xorg.conf.d"
ENABLE_GLDRIVER=false
SKIP_SD_CHECK=false

# Get CLI override (e.g. -browser my-browser or --force)
source $DIR/functions/getopts

# Load local functions
source $DIR/functions/successfull
source $DIR/functions/color

# Enforce this helper to be run as root
if [ $(id -u) -ne 0 ]
then
	echo -e ""
	echo -e " $(color 'red' 'Run this with \e[1msudo\e[0m\e[31m or as an \e[1muser root')"
	echo -e " $(color 'red' 'Since we need to install and configure packages')"
	echo -e " $(color 'red' 'sudo IS needed here!')"
	echo -e ""
	exit 1
fi

# Show introduction
echo -e "$(color 'gregor' ' ╔═╗╔═╗╔══╔═╗╔═╗╔═╗ ')"
echo -e "$(color 'gregor' ' ║ ╦║ ╝╠═ ║ ╦║ ║║ ╝ ')"
echo -e "$(color 'gregor' ' ╚═╝╩ ╩╚══╚═╝╚═╝╩ ╩ ')"
echo -e "$(color 'gregor' 'Setup helper v0.0.1')"
[ $FORCE == true ] && echo -e "$(color 'gregor' 'FORCE mode enabled')"
[ $DEBUG == true ] && echo -e "$(color 'gregor' 'DEBUG mode enabled')"

# Execute steps
source $DIR/functions/setup-steps/01-check-sd
source $DIR/functions/setup-steps/02-boot-to-command
source $DIR/functions/setup-steps/03-dependencies
source $DIR/functions/setup-steps/04-adafruit
source $DIR/functions/setup-steps/05-xorg
source $DIR/functions/setup-steps/06-chromium
source $DIR/functions/setup-steps/07-apache
source $DIR/functions/setup-steps/08-php
source $DIR/functions/setup-steps/09-gregor

# Legacy Xserver
# Try to set Xwrapper.config
sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config 3>/dev/null 1>/dev/null 2>/dev/null

# Finally check if chromium-browser is able to run with the kernel
source $DIR/install-steps/7-check-chromium

# Copy kiosk script
runCmd cp $DIR/scripts/kiosk.sh ~/kiosk.sh
runCmd chmod u+x ~/kiosk.sh

# Show success message
echo ""
echo "$(color 'green' 'Gregor is alive! Go ahead and reboot! Then edit /var/www/html/index.php')"

# Launch Gregor
echo ""
echo "Launching Gregor:"
runCmd service gregor start
successfull $?